# Generated by Django 3.1.3 on 2020-11-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempererature_c', models.CharField(max_length=3)),
                ('measure_date', models.DateTimeField(verbose_name='date measured')),
            ],
        ),
        migrations.CreateModel(
            name='Wind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wind_MperS', models.IntegerField(default=0)),
                ('measure_date', models.DateTimeField(verbose_name='date measured')),
            ],
        ),
    ]
