# Generated by Django 3.1.3 on 2020-11-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20201122_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='temperature_name',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wind',
            name='wind_name',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
    ]
